name: das-v2
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch
  - cpuonly
  - pip:
      - numpy
      - pandas
      - scipy
      - matplotlib
      - seaborn
      - scikit-learn
      - scikit-image
      - pillow
      - tifffile
      - tqdm
      - patsy
      - umap-learn
      - openpyxl
      - xlrd
      - shapely
      - pygame
      - czifile
